version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install all dependencies (including dependencies for running tests)
  pre_build:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - pip install --upgrade pip
      - pip install -r ./vdashboard/requirements.txt -t ./vdashboard
      - rm -rf ./vdashboard/*.dist-info
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
